server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: ${DATABASE_DIALECT}

logging:
  level:
    org.springframework:
      security: ${APP_LOG_LEVEL}
      securityoauth2: ${APP_LOG_LEVEL}